### ISSUE TITLE
demo site gives 404

### ISSUE THREAD

**Issue by Toumash** [rmuif/web#684] opened 2020-10-11 13:33 UTC
## Description

Demo site isn't working. Vercel gives any user "404 not found error"

## Reproduction

1. Go to https://demo.rmuif.com/
2. 404 Page Not Found here :<

## Expected behavior

Working, stable release of the framework.

## Screenshots
![image](https://user-images.githubusercontent.com/9840635/95680059-084bed80-0bd7-11eb-9a8a-26a7edf8ffa1.png)

**Comment by phoqe** [comment] 2020-10-11 16:11
Hello @Toumash, thank you for your bug report. I am investigating this issue and it seems to be related to a build issue that have gone under the radar for a while, I recommend using https://dev.rmuif.com until this is fixed. At the moment, there are no differences.

**Comment by phoqe** [comment] 2020-10-11 18:37
The issue is now fixed. Thanks again.

**Closed by phoqe** 2020-10-11 18:37 UTC
Labels: bug
