### ISSUE TITLE
Error: Cannot find module 'react-dev-utils/crossSpawn'

### ISSUE THREAD

**Issue by majormittens** [rmuif/web#564] opened 2020-04-18 15:23 UTC
## Description

yarn start fails with Error: Cannot find module 'react-dev-utils/crossSpawn' 

## Reproduction

yarn install
yarn start

## Expected behavior

yarn start should work

## Desktop

Node version: 11.12.0
Windows 10 64-bit

**Comment by phoqe** [comment] 2020-04-18 17:03
Did you initialize an app with the command `npx create-react-app my-app --template rmuif`?

**Comment by majormittens** [comment] 2020-04-18 17:23
Yes, I did. Forgot to mention

**Comment by phoqe** [comment] 2020-04-18 17:25
Try removing `node_modules` and `yarn.lock` or `package-lock.json` and run `yarn install` or `npm install` again.

**Comment by majormittens** [comment] 2020-04-19 08:55
I tried reinstalling, initializing another app and even running 
npm i react-dev-utils/crossSpawn --save
npm ERR! Error while executing:
npm ERR! C:\Program Files\Git\cmd\git.EXE ls-remote -h -t ssh://git@github.com/react-dev-utils/crossSpawn.git
npm ERR!
npm ERR! Permission denied (publickey).
npm ERR! fatal: Could not read from remote repository.
npm ERR!
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
npm ERR!
npm ERR! exited with error code: 128

**Comment by phoqe** [comment] 2020-04-19 09:21
Can you try running `yarn install react-dev-utils --dev`? I can't reproduce this issue on my machine, even with a fresh install.

**Comment by majormittens** [comment] 2020-04-19 16:54
Still have the same error. I'm using nvm and I've tested with 12.0.0 as well. Could that be an issue? 

I'll try on a different machine

**Comment by phoqe** [comment] 2020-04-19 18:35
I'm running v13.11.0 so that shouldn't be an issue but please do try it on a different machine. :)

**Comment by phoqe** [comment] 2020-04-21 18:56
@majormittens Can you still reproduce this?

**Comment by phoqe** [comment] 2020-04-23 10:09
Closing this, if you are still having this issue feel free to re-open. Thanks :)

**Closed by phoqe** 2020-04-23 10:09 UTC
Labels: bug
